folio-org/tech-council

- NEW_MODULE_TECH_EVAL.MD
Make several minor adjustments to wording, spelling, grammar, punctuation, etc.
> Cleanup, punctuation, etc.

- module_evaluations/TCR-5_2021-12-08.MD
I should have checked the box in addition to striking out the criteria that was deems NA.  This PR checks the box which I missed.
> TCR-5 - fixing typo

- module_evaluations/TCR-10_2022-2-1.MD
- module_evaluations/TCR-11_2022-2-1.MD
This is the complete review for TCR 10 and TCR 11
> TCR 10 and TCR 11 Evaluation

- NEW_MODULE_TECH_EVAL.MD
This PR adds edits to the supporting documentation section and adds a new section defining the roles involved in the evaluation process.
> Edits pertaining to recent discussions within the TC

- MODULE_ACCEPTANCE_CRITERIA.MD
I noticed that the indentation of some of the sub-bullets is displaying incorrectly.
> Fix Indentation

- module_evaluations/TCR-18_2022-09-23.MD
https://github.com/folio-org/ui-gobi-settings/tree/de4ee6873e87edf1ff186a47e569f0fbde0adb7a meets these criteria.
Refs [TCR-18](https://issues.folio.org/browse/TCR-18)
> TCR-18 ui-gobi-settings review

- module_evaluations/TCR-16_2022-09-28.MD
https://github.com/folio-org/ui-calendar/tree/4d466059157e2abdcff648215694cac05258f637 meets these criteria.
Refs [TCR-16](https://issues.folio.org/browse/TCR-16)
> TCR-16 review ui-calendar

- MODULE_ACCEPTANCE_CRITERIA.MD
The line regarding UX was present twice; this PR fixes that.
> Fix duplicate acceptance criteria

- MODULE_ACCEPTANCE_CRITERIA.MD
- MODULE_EVALUATION_TEMPLATE.MD
The acceptance criteria were updated in June, 2022; the template needs to reflect these changes.
> sync template to criteria from 2022-06-10

- NEW_MODULE_TECH_EVAL.MD
- Added a clause allowing the TC to request that a module be demoed
- Added a clause stating that the TC may vote to override the results of an evaluation
> Added new statements to the processes documentation

- MODULE_ACCEPTANCE_CRITERIA.MD
- MODULE_EVALUATION_TEMPLATE.MD
- NEW_MODULE_TECH_EVAL.MD
> Tc check in

- MODULE_ACCEPTANCE_CRITERIA.MD
- NEW_MODULE_TECH_EVAL.MD
This PR introduces changes intended to make the criteria applicable for FOLIO libraries as well as front and back-end modules.
> Modified criteria and process for the inclusion of folio libraries

- MODULE_EVALUATION_TEMPLATE.MD
This adds a new section to the Module Evaluation Template, which solicits for suggestions that might improve the TCR processes.
> Added a new section to the module evaluation template

- module_evaluations/TCR-32_2023-09-06.MD
https://github.com/folio-org/ui-lists/tree/d2cacd11c5dade464b3d363af1cb158a508dc4b4 meets these criteria.
Refs [TCR-32](https://issues.folio.org/browse/TCR-32)
> TCR-32 ui-lists

- module_evaluations/TCR-30_2023-09-20.MD
Ticket: [TCR-30](https://issues.folio.org/browse/TCR-30).
Security concerns regarding these dependencies these dependencies are noted on the referenced ticket:
- https://github.com/FasterXML/jackson-datatype-jdk8
- https://github.com/FasterXML/jackson-module-jaxb-annotations
This may fail the Value "(6) Module is secure", but there is no straight-forward check box in the evaluation form for this specific convern.
> TCR-30 evaluation.

- module_evaluations/TCR-25_2023-04-19.MD
https://github.com/folio-org/ui-consortia-settings/tree/8f5634e9c4e457508c5cfa38a260a0573ef0c54b meets these criteria.
Refs [TCR-25](https://issues.folio.org/browse/TCR-25)
> TCR-25 ui-consortium-settings

- MODULE_ACCEPTANCE_CRITERIA.MD
- MODULE_EVALUATION_TEMPLATE.MD
- NEW_MODULE_TECH_EVAL.MD
- module_evaluations/README.MD
https://wiki.folio.org/display/TC/TCR+Process+Improvements+-+Fall+2023
> TCR process improvements fall 2023

- MODULE_ACCEPTANCE_CRITERIA.MD
> Drop criterion not to include snapshot versions

- module_evaluations/TCR-45_2024-08-26-mod-record-specifications.MD
Module has been adopted by the TC 10/07/2024
> TCR 45 - mod-record-specifications

- MODULE_ACCEPTANCE_CRITERIA.MD
The recent changes were declared ready to merge at the 2/5 meeting.
> Increment process version number

- module_evaluations/TCR-51_2025_01_10-ui-ld-folio-wrapper.MD
[TCR-51](https://folio-org.atlassian.net/browse/TCR-51)
This is the completed evaluation of the ui-ld-folio-wrapper.
> TCR 51: ui-ld-folio-wrapper

- NEW_MODULE_TECH_EVAL.MD
From conversation at 2025-02-05 TC.  I missed the meeting but watching the recording, figured this is worth putting in writing.
> Notify RSMG after approval

- MODULE_ACCEPTANCE_CRITERIA.MD
- NEW_MODULE_TECH_EVAL.MD
> Add criteria (and template line) to specify the application this module is part of
